### ISSUE TITLE
Reload data with ajax

### ISSUE THREAD

**Issue by obidano** [GrantMStevens/amCharts-Angular#80]
is there any option that can help us reload data  like **AmCharts.loadFile(....)** in jquery ?

**Comment by GrantMStevens** [comment]
You're using Angular, why do you need jquery?

If you want to utilize AmCharts.loadFIle, you'll need to create your own async function that returns the data using a promise. Pseudo code:

```
this.parseCSVData = function(){
    var deferred = $q.defer();

    AmCharts.loadFile( "https://s3-us-west-2.amazonaws.com/s.cdpn.io/t-160/22300.csv", {}, function( response ) {
      var data = AmCharts.parseCSV( response, {
          "useColumnNames": true
        });

      deferred.resolve(data);
    })

    return deferred.promise;
}
```

you can assign the execution of that function to `options` for the chart, which will delay its render till the promise resolves.
